apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  selector:
    app: flask-app
